FROM python:2
RUN pip install docker==2.1.0
RUN pip install kubernetes
RUN pip install pycurl
WORKDIR "/root/"
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
COPY shares_controller.py shares_controller.py
COPY config.json config.json
CMD ["python","-u","shares_controller.py","-v"]
