FROM python:2
RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin/kubectl
RUN pip install docker==2.1.0
RUN pip install kubernetes
COPY isprime.py /src/isprime.py
CMD ["python","-u","/src/isprime.py"]

