apiVersion: v1
kind: Pod
metadata:
  name: isprime
  namespace: hyperpilot
  labels:
     name: isprime-hyperpilot
spec:
      containers:
        - image: index.docker.io/hyperpilot/isprime
          imagePullPolicy: Always
          name: isprime 
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
         - hostPath:
              path: /var/run/docker.sock
           name: docker-sock
