apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: isprimebe-set1
spec:
  template:
    metadata:
      labels:
        name: isprimebe1
        hyperpilot.io/wclass: BE
      annotations:
        scheduler.alpha.kubernetes.io/affinity: >
          {
            "nodeAffinity": {
              "requiredDuringSchedulingIgnoredDuringExecution": {
                "nodeSelectorTerms": [
                  {
                    "matchExpressions": [
                      {
                        "key": "hyperpilot.io/be-enabled",
                        "operator": "In",
                        "values": ["true"]
                      }
                    ]
                  }
                ]
              }
             }
          }
    spec:
      containers:
        - image: index.docker.io/hyperpilot/isprime
          imagePullPolicy: Always
          name: isprime 
          volumeMounts:
            - mountPath: /var/run/docker.sock
              name: docker-sock
          env:
            - name: MY_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
      volumes:
         - hostPath:
              path: /var/run/docker.sock
           name: docker-sock
